apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rhtap-service-push-rpa
  namespace: managed-release-team-tenant1
spec:
  applications:
    - seanworld
  origin: dev-release-team-tenant1
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: https://github.com/seanconroy2021/release-service-catalog.git
        - name: revision
          value: development 
        - name: pathInRepo
          value: pipelines/release-to-github/release-to-github.yaml
      resolver: "git"
    serviceAccountName: release-service-account
  policy: rhtap-service-push-policy
  data:
    targetGHRepo: seanconroy2021/infra-deployments
    githubAppID: 937959
    githubAppInstallationID: 52516361
    mapping:
      components:
        - name: rhtap-service-push-component
          repository: quay.io/sconroykonflux/test-images 
